services:
  dwman:
    image: dwman
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && /app/.venv/bin/python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 /app/main.py",
      ]
    ports:
      - "${PORT:-8000}:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
