name: ci-workflow

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test
  workflow_dispatch:

jobs:
  checks:
    name: run pre-commit hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: j178/prek-action@v1

  tests-unit-frontend:
    name: run unit test for frontend
    defaults:
      run:
        working-directory: ./web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm run test-unit

  tests-backend:
    name: run pytest tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"
      - name: Install cached-poetry
        run: uv sync --locked --all-extras --dev
      - name: Run pytest tests
        run: uv run pytest . --color=yes

  buid_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
    needs:
      - checks
      - tests-backend
      - tests-unit-frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: akorzunin/dwman
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=akorzunin/dwman:buildcache
          cache-to: |
            type=registry,ref=akorzunin/dwman:buildcache,mode=max

  deploy:
    name: Deploy dwman to ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    needs:
      - buid_and_push_to_registry
    environment:
      name: ${{ github.ref_name }}
      url: ${{ vars.DEPLOY_URL }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "sha_short=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v5
        with:
          playbook: deploy.yml
          directory: deploy
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            callback_result_format = yaml
            interpreter_python = /usr/bin/python
            [ssh_connection]
            retries=5
          vault_password: ${{ secrets.ANSIBLE_PASS }}
          inventory: ${{ secrets.ANSIBLE_HOSTS }}
          options: |
            --limit ${{ vars.SERVER_GROUP }}
            --verbose
            --extra-vars "
            IMAGE_TAG=${{ steps.vars.outputs.sha_short }}
            ENVIRONMENT_NAME=${{ github.ref_name }}
            SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}
            SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
            SPOTIPY_REDIRECT_URL=${{ vars.DEPLOY_URL }}/get_token
            API_LOGIN=${{ secrets.API_LOGIN }}
            API_PASSWORD=${{ secrets.API_PASSWORD }}
            PORT=${{ vars.PORT }}
            TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
            IGNORE_CORS=${{ vars.IGNORE_CORS || '' }}
            "
